title: Heron's Knowledge
email: heron.yang.tw@gmail.com
description: >-
  Heron's knowledge base around everything.
url: "knowledge.heron.me"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

exclude: ["CNAME", "Gemfile", "Gemfile.lock", "README.md", "run.sh", "setup.sh"]

# [Theme specific]
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "More about Heron":
    - "http://www.heron.me"

# Makes Aux links open in a new tab.
aux_links_new_tab: true

footer_content: "Copyright &copy; Heron Yang"

# Footer last edited timestamp
last_edit_timestamp: true
color_scheme: dark
# ga_tracking: UA-5555555-55

permalink: pretty

back_to_top: true
back_to_top_text: "Back to top"

collections:
  dev:
    output: true

just_the_docs:
  collections:
    dev:
      name: Development
