title: Heron's Knowledge
email: heron.yang.tw@gmail.com
description: >-
  Heron's knowledge base around everything.
url: "knowledge.heron.me"

source: src
destination: dst

plugins:
  - jekyll-remote-theme

# remote_theme: Drassil/git-wiki-skeleton
