title: Heron's Knowledge
email: heron.yang.tw@gmail.com
description: >-
  Heron's knowledge base around everything.
baseurl: ""
url: "knowledge.heron.me"
repository: heronyang/heronyang.github.io

plugins:
  - jekyll-feed

exclude: ['README.md', 'setup.sh', 'Gemfile.lock', 'Gemfile']
